const INTEGRATION_EVENTS = Object.freeze({
  TASK_COMPLETED: "task.completed",
  TASK_CREATED: "task.created",
  TASK_ASSIGNED: "task.assigned",
  TASK_CANCELLED: "task.cancelled",
  INVENTORY_UPDATED: "inventory.updated",
  ORDER_FULFILLED: "order.fulfilled",
  OPERATOR_STATUS_CHANGED: "operator.status_changed",
  SHIPMENT_READY_FOR_LABEL: "shipment.ready_for_label",
  SHIPMENT_DISPATCHED: "shipment.dispatched",

  INBOUND_ORDER_CREATED: "inbound.order.created",
  INBOUND_ORDER_CANCELLED: "inbound.order.cancelled",
  INBOUND_PRODUCT_SYNCED: "inbound.product.synced",
  INBOUND_SHIPMENT_LABELED: "inbound.shipment.labeled"
});

const OUTBOUND_EVENTS = [
  INTEGRATION_EVENTS.TASK_COMPLETED,
  INTEGRATION_EVENTS.TASK_CREATED,
  INTEGRATION_EVENTS.TASK_ASSIGNED,
  INTEGRATION_EVENTS.TASK_CANCELLED,
  INTEGRATION_EVENTS.INVENTORY_UPDATED,
  INTEGRATION_EVENTS.ORDER_FULFILLED,
  INTEGRATION_EVENTS.OPERATOR_STATUS_CHANGED,
  INTEGRATION_EVENTS.SHIPMENT_READY_FOR_LABEL,
  INTEGRATION_EVENTS.SHIPMENT_DISPATCHED
];

const INBOUND_EVENTS = [
  INTEGRATION_EVENTS.INBOUND_ORDER_CREATED,
  INTEGRATION_EVENTS.INBOUND_ORDER_CANCELLED,
  INTEGRATION_EVENTS.INBOUND_PRODUCT_SYNCED,
  INTEGRATION_EVENTS.INBOUND_SHIPMENT_LABELED
];

module.exports = { INTEGRATION_EVENTS, OUTBOUND_EVENTS, INBOUND_EVENTS };
