const REALTIME_EVENT_TYPES = Object.freeze({
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_UPDATED: "TASK_UPDATED",
  OPERATOR_STATUS_UPDATED: "OPERATOR_STATUS_UPDATED",
  USER_PRESENCE_UPDATED: "USER_PRESENCE_UPDATED",
  USER_LIST_UPDATED: "USER_LIST_UPDATED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  SALES_ORDER_UPDATED: "SALES_ORDER_UPDATED",
  INVENTORY_ALERT: "INVENTORY_ALERT"
});

const REALTIME_EVENT_TYPE_SET = new Set(Object.values(REALTIME_EVENT_TYPES));

module.exports = {
  REALTIME_EVENT_TYPES,
  REALTIME_EVENT_TYPE_SET
};
